POST http://localhost:8080/events
Content-Type: application/json

{
  "name": "Event 1",
  "title": "Event 1 title",
  "description": "Event 1 description",
  "date": "2024-01-01T15:30:00.000Z",
  "location": "Event 1 location",
  "user_id": 1
}